name: update submodule vendor/optimeta from TIBHannover/optimeta-plugin-shared

on:
  # schedule:
  # cron format: minute, hour, day of the month, month, day of the week
  # - cron: "0 6 * * *"
  workflow_dispatch: ~

env:
  GITHUB_TOKEN: ${{ github.token }}
  GH_USERNAME: ${{ github.actor }}

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: all further steps
        run: |

          echo "variables"
          dateTime=$(date +%Y-%m-%d_%H-%M-%S)
          branchName="submodule_optimeta_$dateTime"
          subModuleUrl="https://github.com/TIBHannover/optimeta-plugin-shared"
          subModulePath="vendor/optimeta"
          message="Update $subModulePath from $subModuleUrl on $dateTime"

          echo "setup git username: $GH_USERNAME"
          git config user.email "$GH_USERNAME"
          
          echo "setup git email: $GH_USERNAME@users.noreply.github.com"
          git config user.name "$GH_USERNAME@users.noreply.github.com"
          
          echo "remove directory $subModulePath recursively"
          rm -rf $subModulePath

          echo "checkout to new local branch with name $branchName"
          git checkout -b $branchName

          echo "clone $subModuleUrl to path $subModulePath"
          git clone "$subModuleUrl" "$subModulePath"
          
          echo "remove directory $subModulePath/.git recursively"
          rm -rf "$subModulePath/.git"

          echo "create file $subModulePath/_$dateTime.txt"
          echo "$dateTime" > "$subModulePath/_$dateTime.txt"

          echo "add directory $subModulePath recursively"
          git add --all $subModulePath

          echo "commit all changes with message: $message"
          git commit -m "$message"

          echo "push to new branch with name: $branchName"
          git push -u origin $branchName

          echo "create pull request with label and body: $message"
          gh pr create --title "$message" --body "$message"
          
          echo "end"
