name: update_submodule_optimeta
env:
  GITHUB_TOKEN: ${{ github.token }}
on:
  # schedule:
  # cron format: minute, hour, day of the month, month, day of the week
  # - cron: "0 6 * * *"
  workflow_dispatch: ~

jobs:
  update_submodule_optimeta:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: all further steps
        run: |
          
          # variables
          dateTime=$(date +%Y-%m-%d_%H-%M-%S)
          branchName="update_submodule_optimeta_$dateTime"
          userName="GaziYucel"
          userEmail="<84437883+GaziYucel@users.noreply.github.com>"
          
          # setup git config username and email
          git config user.name $userName
          git config user.email $userEmail
          
          # remove directory recursively vendor/optimeta
          rm -rf vendor/optimeta

          # checkout to new local branch
          git checkout -b $branchName

          # git clone TIBHannover/optimeta-plugin-shared > vendor/optimeta
          git clone https://github.com/TIBHannover/optimeta-plugin-shared vendor/optimeta

          # remove directory recursively vendor/optimeta/.git
          rm -rf vendor/optimeta/.git

          # create vendor/optimeta/_updated_$dateTime.txt
          touch "vendor/optimeta/_updated_$dateTime.txt"

          # git add everything in directory vendor/optimeta
          git add --all vendor/optimeta

          # git commit
          git commit -m "Update submodule TIBHannover/optimeta-plugin-shared > vendor/optimeta"

          # git push to new branch name
          git push -u origin $branchName

          # create new pull-request
          gh pr create --title "Update submodule TIBHannover/optimeta-plugin-shared > vendor/optimeta $dateTime" --body "branch name $branchName"
